export enum ErrorCode {
  FORBIDDEN = 'FORBIDDEN REQUEST',
  NOT_FOUND = 'NOT FOUND',
  NOT_FOUND_PLAYER = 'NOT_FOUND_PLAYER',
  STATUS_NOT_FOUND = '404',
  STATUS_INTERNAL_SERVER_ERROR = 'STATUS_INTERNAL_SERVER_ERROR',
}

export enum HttpStatus {
  BAD_REQUEST = 400,
}
