export enum ErrorCode {
  FORBIDDEN = 'FORBIDDEN REQUEST',
  NOT_FOUND = 'NOT FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  STATUS_NOT_FOUND = '404',
  PASSWORD_NOT_MATCH = 'PASSWORD_NOT_MATCH',
  LOGIN_FAIL = 'LOGIN_FAIL',
  STATUS_INTERNAL_SERVER_ERROR = 'STATUS_INTERNAL_SERVER_ERROR',
}

export enum HttpStatus {
  BAD_REQUEST = 400,
}
